Repository JoinColony/colonyJS, pull requests merged in 2018-07, with the labels that each got.

#234 Add event processors for new task change events
  packages/colony-js-client/src/ColonyClient/index.js
Labels: Code review me!!11one

#235 Mention newly added task events in changelog
  CHANGELOG.md
Labels: Code review me!!11one

#232 Add `waitForTransactionReceipt` abstraction to adapters
  CHANGELOG.md
  packages/colony-js-adapter-ethers/src/EthersAdapter.js
  packages/colony-js-adapter-ethers/src/__tests__/EthersAdapter.test.js
  packages/colony-js-adapter-ethers/src/defaults.js
  packages/colony-js-adapter/interface/Adapter.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/classes/ContractMethodSender.js
Labels: New feature, maintenance

#233 Check domain ID when creating task
  CHANGELOG.md
  package.json
  packages/colony-js-adapter/interface/EventHandlers.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyClient/senders/CreateTask.js
  packages/colony-js-contract-client/src/__tests__/ContractMethod.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/__tests__/paramValidation.js
  packages/colony-js-contract-client/src/classes/ContractClient.js
  packages/colony-js-contract-client/src/classes/ContractEvent.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
  packages/colony-js-contract-client/src/flowtypes/index.js
  packages/colony-js-contract-client/src/flowtypes/methods.js
  packages/colony-js-contract-client/src/flowtypes/params.js
  packages/colony-js-contract-client/src/flowtypes/signatures.js
  packages/colony-js-contract-client/src/modules/paramConversion.js
  packages/colony-js-contract-client/src/modules/paramValidation.js
  yarn.lock
Labels: Code review me!!11one, enhancement, maintenance

#236 Fix wrong role conceptions in documentation
  docs/_API_ColonyClient.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: documentation
