Repository JoinColony/colonyJS, pull requests merged in 2018-11, with the labels that each got.

#295 Misc. `registerUserLabel` fixes
  CHANGELOG.md
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/flowtypes/methods.js
  packages/colony-js-contract-client/src/mocks/mockValues.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
Labels: bug

#296 Add missing multisig types
  docs/_API_ColonyClient.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: documentation

#297 Fix `registerColonyLabel` parameters
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: bug

#303 Add new contract methods/events
  CHANGELOG.md
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/addRecoveryMethods.js
Labels: maintenance

#310 Handle invalid UTF8 hex strings
  .flowconfig
  CHANGELOG.md
  docs/_API_ColonyClient.md
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
  packages/colony-js-contract-loader/src/ContractLoader.js
Labels: Code review me!!11one

#311 Remove `AuthorityClient`
  CHANGELOG.md
  docs/_API_ColonyClient.md
  docs/_API_MetaColonyClient.md
  packages/colony-js-client/docs/_API_AuthorityClient.template.md
  packages/colony-js-client/docs/_API_ColonyClient.template.md
  packages/colony-js-client/docs/_API_MetaColonyClient.template.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/AuthorityClient/index.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/MetaColonyClient/index.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
  packages/colony-js-client/src/constants.js
  packages/colony-js-client/src/index.js
Labels: maintenance, ready-for-merge

#309 Update task lifecycle document
  docs/_Docs_TaskLifecycle.md
Labels: ready-for-merge
