Repository JoinColony/colonyJS, pull requests merged in 2018-05, with the labels that each got.

#112 Update greenkeeper badge image
  README.md
Labels: greenkeeper, maintenance

#118 Fix indentation on ‘Get Started’ code sample
  docs/_Docs_GetStarted.md
Labels: documentation

#116 Add `babel-runtime` dependency
  packages/colony-js-adapter-ethers/package.json
  packages/colony-js-client/package.json
  packages/colony-js-contract-client/package.json
  packages/colony-js-contract-loader-http/package.json
  packages/colony-js-utils/package.json
  yarn.lock
Labels: Code review me!!11one, bug

#102 Specify node/yarn versions with `engines` in all `package.json` files
  package.json
  packages/colony-js-adapter-ethers/package.json
  packages/colony-js-adapter/package.json
  packages/colony-js-client/package.json
  packages/colony-js-contract-client/package.json
  packages/colony-js-contract-loader-http/package.json
  packages/colony-js-contract-loader/package.json
  packages/colony-js-utils/package.json
Labels: maintenance

#120 Doc fixes and improvements
  docs/_Docs_Multisignature.md
  docs/_Docs_Overview.md
  docs/_Docs_Quickstart.md
  docs/_Index.md
  docs/doc.config.json
Labels: Code review me!!11one

#124 Update ColonyNetworkClient for recent contract changes
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/callers/GetTask.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractMethodCaller.js
  packages/colony-js-contract-client/src/modules/getMethodArgs.js
Labels: maintenance

#121 Add declarative parameter type mapping for ContractMethods
  .eslintrc
  flow-typed/npm/jest_v22.x.x.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
  packages/colony-js-contract-client/src/__tests__/ContractMethod.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodCaller.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/__tests__/getMethodArgs.js
  packages/colony-js-contract-client/src/__tests__/getMethodReturnValue.js
  packages/colony-js-contract-client/src/__tests__/inputValidation.js
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/__tests__/validate.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractMethodCaller.js
  packages/colony-js-contract-client/src/classes/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/classes/ContractMethodSender.js
  packages/colony-js-contract-client/src/flowtypes.js
  packages/colony-js-contract-client/src/index.js
  packages/colony-js-contract-client/src/modules/getMethodArgs.js
  packages/colony-js-contract-client/src/modules/getMethodReturnValue.js
  packages/colony-js-contract-client/src/modules/inputValidation.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
  packages/colony-js-contract-client/src/modules/validate.js
Labels: Code review me!!11one, enhancement

#122 Add 'bignumber' parameter type
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/flowtypes.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
  packages/colony-js-utils/src/isBigNumber.js
Labels: Code review me!!11one, New feature, documentation

#123 Add 'role' custom parameter type
  docs/_API_ColonyClient.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/__tests__/paramTypes.test.js
  packages/colony-js-client/src/constants.js
  packages/colony-js-client/src/index.js
  packages/colony-js-client/src/paramTypes.js
Labels: Code review me!!11one, New feature, documentation

#125 Remove separate success/error event handling
  packages/colony-js-adapter-ethers/src/EthersAdapter.js
  packages/colony-js-adapter-ethers/src/__tests__/EthersAdapter.test.js
  packages/colony-js-adapter/interface/EventHandlers.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
  packages/colony-js-contract-client/src/__tests__/ContractClient.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
Labels: maintenance

#130 Refresh new MultisigOperations
  docs/_Docs_Multisignature.md
  packages/colony-js-contract-client/src/__tests__/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/classes/ContractMethodMultisigSender.js
Labels: bug, documentation

#126 Better handling for 'empty' responses
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  packages/colony-js-client/src/ColonyClient/callers/GetTask.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodCaller.js
  packages/colony-js-contract-client/src/classes/ContractMethodCaller.js
  packages/colony-js-contract-client/src/flowtypes.js
  packages/colony-js-utils/src/isBigNumber.js
Labels: Code review me!!11one, documentation, enhancement

#132 Update docs with recent changes
  docs/_Docs_ContractClient.md
  docs/_Docs_GetStarted.md
  docs/_Docs_Quickstart.md
Labels: Code review me!!11one, documentation

#135 Bug fix: Convert non-hex string input values to hex
  CHANGELOG.md
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
Labels: Code review me!!11one, bug

#136 Fix `ROLES` values
  CHANGELOG.md
  packages/colony-js-client/src/constants.js
Labels: bug

#137 Update ethers to 3.0.17 (from 3.0.3)
  CHANGELOG.md
  packages/colony-js-adapter-ethers/package.json
  yarn.lock
Labels: maintenance

#141 Maintain nonce value
  CHANGELOG.md
  docs/_API_MultisigOperation.md
  docs/_Docs_Multisignature.md
  packages/colony-js-contract-client/src/__tests__/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/__tests__/MultisigOperation.js
  packages/colony-js-contract-client/src/classes/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/classes/MultisigOperation.js
  packages/colony-js-contract-client/src/flowtypes.js
Labels: Code review me!!11one, bug, documentation, enhancement

#142 Use fixed lerna mode
  CHANGELOG.md
  lerna.json
Labels: maintenance

#145 Set Sender's `defaultGasLimit` as a number
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/classes/ContractMethodSender.js
Labels: Code review me!!11one, bug
