Repository JoinColony/colonyJS, pull requests merged in 2018-06, with the labels that each got.

#160 Add 'empty' IPFS hash output validation
  CHANGELOG.md
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
  packages/colony-js-utils/src/__tests__/checkValidAddress.js
  packages/colony-js-utils/src/checkValidAddress.js
  packages/colony-js-utils/src/constants.js
  packages/colony-js-utils/src/index.js
  packages/colony-js-utils/src/isEmptyHexString.js
  packages/colony-js-utils/src/isValidAddress.js
Labels: Code review me!!11one, bug

#161 Define default values for Caller/Sender params
  CHANGELOG.md
  docs/_API_ColonyClient.md
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/constants.js
  packages/colony-js-contract-client/src/__tests__/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
  packages/colony-js-contract-client/src/flowtypes.js
  packages/colony-js-contract-client/src/modules/inputValidation.js
Labels: Code review me!!11one, enhancement

#163 Provide better context for method validation
  CHANGELOG.md
  packages/colony-js-contract-client/src/__tests__/ContractClient.js
  packages/colony-js-contract-client/src/__tests__/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractClient.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractMethodCaller.js
  packages/colony-js-contract-client/src/classes/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/flowtypes.js
Labels: Code review me!!11one, enhancement

#164 (Inter)dependency cleanup
  .babelrc
  .editorconfig
  CHANGELOG.md
  package.json
  packages/colony-js-adapter-ethers/.babelrc
  packages/colony-js-adapter-ethers/package.json
  packages/colony-js-adapter/package.json
  packages/colony-js-client/.babelrc
  packages/colony-js-client/package.json
  packages/colony-js-contract-client/.babelrc
  packages/colony-js-contract-client/package.json
  packages/colony-js-contract-loader-http/.babelrc
  packages/colony-js-contract-loader-http/package.json
  packages/colony-js-contract-loader/package.json
  packages/colony-js-utils/.babelrc
  packages/colony-js-utils/package.json
  yarn.lock
Labels: maintenance

#166 Better parameter validation
  CHANGELOG.md
  packages/colony-js-contract-client/src/__tests__/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
Labels: bug

#168 Fix timestamp parsing
  CHANGELOG.md
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
Labels: bug

#167 Fix Truffle migrate, highlight colonyNetwork commit
  docs/_Docs_GetStarted.md
Labels: documentation

#183 Contract events subscription
  CHANGELOG.md
  packages/colony-js-adapter-ethers/src/EthersAdapter.js
  packages/colony-js-adapter-ethers/src/EthersContract.js
  packages/colony-js-adapter-ethers/src/__tests__/EthersContract.test.js
  packages/colony-js-adapter/index.js
  packages/colony-js-adapter/interface/Contract.js
  packages/colony-js-adapter/interface/EventHandlers.js
  packages/colony-js-client/src/ColonyClient/callers/GetTask.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/__tests__/paramTypes.test.js
  packages/colony-js-contract-client/src/__tests__/ContractClient.js
  packages/colony-js-contract-client/src/__tests__/ContractEvent.js
  packages/colony-js-contract-client/src/__tests__/ContractMethod.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodCaller.js
  packages/colony-js-contract-client/src/__tests__/inputValidation.js
  packages/colony-js-contract-client/src/__tests__/paramConversion.js
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/__tests__/paramValidation.js
  packages/colony-js-contract-client/src/classes/ContractClient.js
  packages/colony-js-contract-client/src/classes/ContractEvent.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractMethodCaller.js
  packages/colony-js-contract-client/src/flowtypes.js
  packages/colony-js-contract-client/src/mocks/MockEmittingContract.js
  packages/colony-js-contract-client/src/mocks/mockValues.js
  packages/colony-js-contract-client/src/modules/inputValidation.js
  packages/colony-js-contract-client/src/modules/paramConversion.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
  packages/colony-js-contract-client/src/modules/paramValidation.js
Labels: New feature, enhancement

#180 Add token and authority clients
  CHANGELOG.md
  docs/_API_AuthorityClient.md
  docs/_API_ColonyClient.md
  docs/_API_TokenClient.md
  docs/_Docs_ContractClient.md
  docs/_Docs_GetStarted.md
  docs/_Docs_Multisignature.md
  packages/colony-js-client/docs/_API_AuthorityClient.template.md
  packages/colony-js-client/docs/_API_TokenClient.template.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/AuthorityClient/index.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
  packages/colony-js-client/src/__tests__/paramTypes.test.js
  packages/colony-js-client/src/constants.js
  packages/colony-js-client/src/index.js
  packages/colony-js-client/src/paramTypes.js
  packages/colony-js-contract-client/src/__tests__/ContractMethod.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/__tests__/MultisigOperation.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/classes/MultisigOperation.js
  packages/colony-js-contract-client/src/flowtypes.js
Labels: New feature, bug, documentation

#185 Ignore extra parameters
  CHANGELOG.md
  packages/colony-js-contract-client/src/__tests__/paramValidation.js
  packages/colony-js-contract-client/src/modules/paramValidation.js
Labels: bug

#186 Minor loader changes
  docs/_API_ColonyClient.md
  docs/_Docs_GetStarted.md
  packages/colony-js-contract-loader/src/defaults.js
  packages/colony-js-contract-loader/src/interface/ContractLoader.js
  packages/colony-js-contract-loader/src/transforms/truffleTransform.js
Labels: Code review me!!11one, enhancement

#189 Supply network to transform method for Loaders
  CHANGELOG.md
  packages/colony-js-contract-loader-http/src/__tests__/index.js
  packages/colony-js-contract-loader/src/interface/ContractLoader.js
  packages/colony-js-contract-loader/src/transforms/truffleTransform.js
Labels: Code review me!!11one, bug

#190 Wait for in-progress transactions to be mined before finding the receipt
  CHANGELOG.md
  packages/colony-js-adapter-ethers/src/EthersAdapter.js
  packages/colony-js-adapter/interface/Adapter.js
  packages/colony-js-adapter/interface/Provider.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/classes/ContractMethodSender.js
  packages/colony-js-contract-client/src/defaults.js
Labels: enhancement

#191 Ensure transaction receipt is received for clients with no mining time
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/classes/ContractMethodSender.js
Labels: Code review me!!11one, bug

#193 Improve consistency of token attribute
  CHANGELOG.md
  docs/_API_ColonyClient.md
  docs/_API_Loaders.md
  docs/_Docs_GetStarted.md
  docs/_Docs_Loaders.md
  packages/colony-js-client/docs/_API_ColonyClient.template.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/paramTypes.js
  packages/colony-js-contract-client/src/flowtypes.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
Labels: documentation

#204 Improve getTokenInfo
  CHANGELOG.md
  packages/colony-js-client/src/TokenClient/callers/GetTokenInfo.js
Labels: Code review me!!11one

#208 Remove mocks for `paramTypes` tests
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
Labels: maintenance

#207 Get wallet address with `getAddress`
  CHANGELOG.md
  packages/colony-js-adapter/interface/Wallet.js
  packages/colony-js-contract-client/src/__tests__/MultisigOperation.js
  packages/colony-js-contract-client/src/classes/MultisigOperation.js
Labels: Code review me!!11one, bug

#209 Add hexString type
  CHANGELOG.md
  docs/_API_ColonyClient.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/flowtypes.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
Labels: Code review me!!11one, bug

#211 Fix `TaskDueDateChanged` event parameter type
  packages/colony-js-client/src/ColonyClient/index.js
Labels: maintenance

#222 Change mintTokens type to BigNumber
  docs/_API_ColonyClient.md
  docs/_Docs_GetStarted.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: documentation

#225 Add `DomainAdded`/`PotAdded` events
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: Code review me!!11one, maintenance

#227 Improve test coverage for colony-js-contract-loader-fs
  packages/colony-js-contract-loader-fs/src/__tests__/FSLoader.test.js
  packages/colony-js-contract-loader-fs/src/__tests__/TruffleLoader.test.js
  packages/colony-js-contract-loader-fs/src/__tests__/index.js
Labels: Code review me!!11one

#228 Fix flaky tests
  packages/colony-js-adapter-ethers/src/__tests__/EthersAdapter.test.js
Labels: maintenance

#229 Pad input hex strings (`tokenAddress` param type)
  CHANGELOG.md
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
  packages/colony-js-utils/src/__tests__/isEmptyHexString.js
  packages/colony-js-utils/src/isEmptyHexString.js
Labels: Code review me!!11one, bug
