Repository JoinColony/colonyJS, pull requests merged in 2018-12, with the labels that each got.

#314 Update `cancelTask` to multisig sender
  CHANGELOG.md
  docs/_API_ColonyClient.md
  docs/_Docs_TaskLifecycle.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: ready-for-review

#315 Update `setTaskDomain` to multisig sender
  CHANGELOG.md
  docs/_API_ColonyClient.md
  docs/_Docs_TaskLifecycle.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: ready-for-review

#316 Remove `engines -> yarn` version requirement
  CHANGELOG.md
  package.json
  packages/colony-js-adapter-ethers/package.json
  packages/colony-js-adapter/package.json
  packages/colony-js-client/package.json
  packages/colony-js-contract-client/package.json
  packages/colony-js-contract-loader-fs/package.json
  packages/colony-js-contract-loader-http/package.json
  packages/colony-js-contract-loader/package.json
  packages/colony-js-utils/package.json
Labels: maintenance

#317 Update input and event for `addDomain`
  docs/_API_ColonyClient.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: ready-for-review

#312 Docs fixes/improvements/backlog
  docs/_API_AuthorityClient.md
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  docs/_API_ContractClient.md
  docs/_API_ContractLoader.md
  docs/_API_ContractMethodCaller.md
  docs/_API_ContractMethodMultiSigSender.md
  docs/_API_ContractMethodSender.md
  docs/_API_MetaColonyClient.md
  docs/_API_MultisigOperation.md
  docs/_API_TokenClient.md
  docs/_Docs_Adapters.md
  docs/_Docs_Authority.md
  docs/_Docs_Clients.md
  docs/_Docs_DomainsAndSkills.md
  docs/_Docs_GetStarted.md
  docs/_Docs_Loaders.md
  docs/_Docs_ManagingFunds.md
  docs/_Docs_Multisignature.md
  docs/_Docs_Overview.md
  docs/_Docs_TaskLifecycle.md
  docs/_Docs_UsingIPFS.md
  packages/colony-js-client/docs/_API_ColonyClient.template.md
  packages/colony-js-client/docs/_API_ColonyNetworkClient.template.md
  packages/colony-js-client/docs/_API_MetaColonyClient.template.md
  packages/colony-js-client/docs/_API_TokenClient.template.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: documentation, in-progress

#320 Add event log parsing
  packages/colony-js-adapter/index.js
  packages/colony-js-adapter/interface/Contract.js
  packages/colony-js-adapter/interface/Provider.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/__tests__/ColonyClient.test.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
  packages/colony-js-contract-client/src/__tests__/ContractClient.js
  packages/colony-js-contract-client/src/__tests__/ContractEvent.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/classes/ContractClient.js
  packages/colony-js-contract-client/src/classes/ContractEvent.js
Labels: New feature, ready-for-merge

#321 Refactor ContractClient.getLogs, split parsing into getEvents
  CHANGELOG.md
  packages/colony-js-contract-client/src/classes/ContractClient.js
Labels: enhancement

#326 Add `getParentSkillId` and `getChildSkillId` examples
  docs/_Docs_DomainsAndSkills.md
Labels: ready-for-review

#325 Explain task properties and add "Fund Task"
  docs/_Docs_TaskLifecycle.md
Labels: ready-for-merge

#324 Add Docker install instructions to "Get Started"
  docs/_Docs_GetStarted.md
  docs/_Docs_TaskLifecycle.md
Labels: ready-for-merge

#327 Initialize clients before returning
  packages/colony-js-client/src/ColonyNetworkClient/index.js
Labels: ready-for-review

#329 Fix event titles and links in doc generator
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  docs/_API_MetaColonyClient.md
  docs/_API_TokenClient.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/index.js
Labels: ready-for-review
