Repository JoinColony/colonyJS, pull requests merged in 2018-09, with the labels that each got.

#253 Upgrade ColonyNetworkClient for current IColonyNetwork spec
  docs/_API_ColonyNetworkClient.md
  packages/colony-js-client/src/ColonyNetworkClient/index.js
Labels: Code review me!!11one, maintenance

#254 Parse all method events with ContractEvent
  CHANGELOG.md
  docs/_API_AuthorityClient.md
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  docs/_API_TokenClient.md
  docs/_Docs_ContractClient.md
  packages/colony-js-adapter-ethers/src/EthersAdapter.js
  packages/colony-js-adapter-ethers/src/__tests__/EthersAdapter.test.js
  packages/colony-js-adapter/index.js
  packages/colony-js-adapter/interface/Adapter.js
  packages/colony-js-adapter/interface/Contract.js
  packages/colony-js-adapter/interface/Event.js
  packages/colony-js-adapter/interface/TransactionReceipt.js
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
  packages/colony-js-contract-client/src/__tests__/ContractClient.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/classes/ContractClient.js
  packages/colony-js-contract-client/src/classes/ContractEvent.js
  packages/colony-js-contract-client/src/classes/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/classes/ContractMethodSender.js
  packages/colony-js-contract-client/src/flowtypes/methods.js
  packages/colony-js-contract-client/src/modules/paramConversion.js
Labels: Code review me!!11one, documentation, enhancement, maintenance

#256 Update ethers to 3.0.27
  packages/colony-js-adapter-ethers/package.json
  yarn.lock
Labels: maintenance

#255 Upgrade ColonyClient for current IColony spec
  CHANGELOG.md
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  packages/colony-js-client/src/AuthorityClient/index.js
  packages/colony-js-client/src/ColonyClient/callers/GetTask.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyClient/senders/CreateTask.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/constants.js
  packages/colony-js-client/src/index.js
  packages/colony-js-client/src/paramTypes.js
  packages/colony-js-contract-client/src/__tests__/MultisigOperation.js
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/classes/MultisigOperation.js
  packages/colony-js-contract-client/src/flowtypes/params.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
Labels: maintenance, not ready

#259 Increase createColony gasLimit
  CHANGELOG.md
  packages/colony-js-client/src/ColonyNetworkClient/index.js
Labels: bug

#260 Update senders
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: bug, documentation

#267 Parse EtherscanLoader result (ABI) as JSON
  CHANGELOG.md
  packages/colony-js-contract-loader-http/src/__tests__/index.js
  packages/colony-js-contract-loader-http/src/loaders/EtherscanLoader.js
Labels: bug

#271 Fix flow errors with ContractClient
  CHANGELOG.md
  packages/colony-js-contract-client/src/classes/MultisigOperation.js
  packages/colony-js-contract-client/src/flowtypes/methods.js
Labels: maintenance
