Repository JoinColony/colonyJS, pull requests merged in 2018-10, with the labels that each got.

#273 Parse `SkillAdded` event properly when emitted via `ColonyClient`
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-contract-client/src/classes/ContractMethodSender.js
Labels: bug

#276 Add type exports
  CHANGELOG.md
  packages/colony-js-client/src/index.js
  packages/colony-js-contract-client/src/index.js
Labels: Code review me!!11one, maintenance

#278 Add ENS functionality
  CHANGELOG.md
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
Labels: Code review me!!11one

#285 Supply options for `createToken` (make it a `Sender`)
  CHANGELOG.md
  docs/_API_ColonyNetworkClient.md
  docs/_Docs_GetStarted.md
  packages/colony-js-adapter/interface/Provider.js
  packages/colony-js-client/docs/_API_ColonyNetworkClient.template.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/senders/CreateToken.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
Labels: enhancement

#286 Fix `getTaskRole` return value
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: bug

#290 Add token events conditionally
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/__tests__/ColonyClient.test.js
Labels: bug
