Repository JoinColony/colonyJS, pull requests merged in 2019-02, with the labels that each got.

#351 Fix and update colony client methods and events
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  docs/_API_TokenClient.md
  package.json
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/TokenLockingClient/index.js
  packages/colony-js-client/src/__tests__/ColonyClient.test.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
  packages/colony-js-client/src/__tests__/paramTypes.test.js
  packages/colony-js-client/src/addMetaColonyMethods.js
  packages/colony-js-client/src/addTokenLockingMethods.js
  packages/colony-js-client/src/constants.js
  packages/colony-js-client/src/index.js
  packages/colony-js-client/src/paramTypes.js
Labels: ready-for-review

#352 Add `getNetworkClient` to colony-js-client
  CHANGELOG.md
  README.md
  docs/_Components_Clients.md
  docs/_Intro_GetStarted.md
  packages/colony-js-client/package.json
  packages/colony-js-client/src/getNetworkClient.js
  packages/colony-js-client/src/index.js
  yarn.lock
Labels: in-progress

#354 Add local support for `getNetworkLoader`
  CHANGELOG.md
  docs/_Components_Clients.md
  docs/_Intro_GetStarted.md
  docs/_Intro_LocalSetup.md
  packages/colony-js-client/package.json
  packages/colony-js-client/src/getNetworkClient.js
Labels: ready-for-review

#360 Add Rinkeby v3 network loader
  package.json
  packages/colony-js-contract-loader-network/config.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v1/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v1/Token.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/Token.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/DSToken.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/IColonyNetwork.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/IMetaColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/IRecovery.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/ITokenLocking.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/OneTxPayment.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/Token.json
  packages/colony-js-contract-loader-network/src/NetworkLoader.js
  packages/colony-js-contract-loader-network/src/__tests__/NetworkLoader.test.js
Labels: maintenance, ready-for-review

#361 Add EthersWrappedWallet to colony-js-client
  packages/colony-js-client/package.json
  packages/colony-js-client/src/getNetworkClient.js
  packages/colony-js-client/src/lib/EthersWrappedWallet/index.js
  packages/colony-js-client/src/lib/EthersWrappedWallet/types.js
  yarn.lock
Labels: ready-for-review

#366 Minor fixes to "Local Setup" instructions
  docs/_Intro_LocalSetup.md
Labels: in-progress

#369 Minor fixes and improvements to use of EWW
  packages/colony-js-client/src/getNetworkClient.js
  packages/colony-js-client/src/lib/EthersWrappedWallet/index.js
Labels: ready-for-review

#371 Add missing event types
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: bug

#372 Fix transaction retrieval after sending in EWW
  CHANGELOG.md
  packages/colony-js-client/src/lib/EthersWrappedWallet/index.js
Labels: ready-for-review
