Repository JoinColony/colonyJS, pull requests merged in 2019-07, with the labels that each got.

#428 Don't set nonce values for MetaMask (`EthersWrappedWallet`)
  packages/colony-js-client/src/lib/EthersWrappedWallet/index.js
Labels: bug, ready-for-review

#431 Fix task role change parameter
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: bug, ready-for-review

#432 Add verbse option to ContractClient
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/getColonyClient.js
  packages/colony-js-client/src/getNetworkClient.js
  packages/colony-js-contract-client/src/classes/ContractClient.js
  packages/colony-js-contract-client/src/classes/ContractEvent.js
  packages/colony-js-contract-client/src/flowtypes/methods.js
Labels: enhancement, ready-for-review

#434 Supply optional `network` property to HTTP loaders
  CHANGELOG.md
  packages/colony-js-contract-loader-http/src/flowtypes.js
  packages/colony-js-contract-loader-http/src/loaders/HttpLoader.js
  packages/colony-js-contract-loader-http/src/loaders/TrufflepigLoader.js
Labels: bug, ready-for-review

#435 Add v3 deploys to NetworkLoader
  CHANGELOG.md
  packages/colony-js-contract-loader-network/contracts/versioned/v3/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/IColonyNetwork.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/IMetaColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/IRecovery.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/ITokenLocking.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/OldRoles.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/OldRolesFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/OneTxPayment.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/OneTxPaymentFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/Token.json
  packages/colony-js-contract-loader-network/contracts/versioned/v3/TokenAuthority.json
  packages/colony-js-contract-loader-network/src/NetworkLoader.js
Labels: under-review
