Repository JoinColony/colonyJS, pull requests merged in 2019-06, with the labels that each got.

#416 Fix input name for `makeExecuteTaskRoleChange`
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: bug

#421 Upgrade for glider
  CHANGELOG.md
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  docs/_API_TokenClient.md
  docs/_API_TokenLockingClient.md
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyClient/senders/DomainAuth.js
  packages/colony-js-client/src/ColonyNetworkClient/callers/LookupRegisteredENSDomain.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/TokenLockingClient/index.js
  packages/colony-js-client/src/__tests__/ColonyClient.test.js
  packages/colony-js-client/src/getNetworkClient.js
  packages/colony-js-contract-client/package.json
  packages/colony-js-contract-client/src/classes/ContractClient.js
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/IColonyNetwork.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/IMetaColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/IRecovery.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/ITokenLocking.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/OldRoles.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/OldRolesFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/OneTxPayment.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/OneTxPaymentFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/Token.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v2/TokenAuthority.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v1/Authority.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v1/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v1/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v1/IColonyNetwork.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v1/Token.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/Authority.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/IColonyNetwork.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/Token.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/DSToken.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/OneTxPayment.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/Token.json
  packages/colony-js-contract-loader-network/src/NetworkLoader.js
  packages/colony-js-contract-loader-network/src/__tests__/NetworkLoader.test.js
  yarn.lock
Labels: ready-for-review

#420 Add getColonyClient export method
  CHANGELOG.md
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/getColonyClient.js
  packages/colony-js-client/src/getNetworkClient.js
  packages/colony-js-client/src/index.js
Labels: enhancement, ready-for-review

#422 Update network loader to support mainnet
  CHANGELOG.md
  packages/colony-js-client/src/getNetworkClient.js
  packages/colony-js-contract-loader-network/contracts/versioned/v1/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/IColonyNetwork.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/IMetaColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/IRecovery.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/ITokenLocking.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/OldRoles.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/OldRolesFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/OneTxPayment.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/OneTxPaymentFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/Token.json
  packages/colony-js-contract-loader-network/contracts/versioned/v1/TokenAuthority.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/IColonyNetwork.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/IMetaColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/IRecovery.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/ITokenLocking.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/OldRoles.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/OldRolesFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/OneTxPayment.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/OneTxPaymentFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/Token.json
  packages/colony-js-contract-loader-network/contracts/versioned/v2/TokenAuthority.json
  packages/colony-js-contract-loader-network/src/NetworkLoader.js
  packages/colony-js-contract-loader-network/src/__tests__/NetworkLoader.test.js
Labels: enhancement, ready-for-review

#424 Fix LookupRegisteredENSDomain caller for empty response
  packages/colony-js-client/src/ColonyNetworkClient/callers/LookupRegisteredENSDomain.js
Labels: bug

#423 Update docs, register ENS, and get reputation
  CHANGELOG.md
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  docs/_API_TokenLockingClient.md
  docs/_Components_Clients.md
  docs/_Topics_RegisteringENSLabels.md
  docs/_Topics_ReputationAndRewards.md
  docs/_Topics_UsingIPFS.md
  docs/_Topics_UsingMultisignature.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
Labels: documentation, maintenance

#425 Use DomainAuth in MakePayment estimate method
  packages/colony-js-client/src/ColonyClient/senders/MakePayment.js
Labels: bug

#426 Update docs and token client params
  CHANGELOG.md
  docs/_API_TokenClient.md
  docs/_Intro_GetStarted.md
  docs/_Topics_RegisteringENSLabels.md
  docs/_Topics_TokensAndFunding.md
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/lib/EthersWrappedWallet/index.js
Labels: documentation, maintenance, ready-for-review
