Repository JoinColony/colonyJS, pull requests merged in 2019-05, with the labels that each got.

#391 Add createTokenAuthority sender to TokenClient
  CHANGELOG.md
  docs/_API_TokenClient.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/TokenClient/senders/CreateTokenAuthority.js
Labels: under-review

#395 Correct Token contractName and params
  packages/colony-js-client/src/ColonyNetworkClient/senders/CreateToken.js
  packages/colony-js-client/src/__tests__/ColonyNetworkClient.test.js
Labels: bug

#398 Fix custom senders to correctly estimate
  packages/colony-js-client/src/ColonyClient/senders/AddExtension.js
  packages/colony-js-client/src/ColonyClient/senders/MakePayment.js
  packages/colony-js-client/src/ColonyClient/senders/RemoveExtension.js
  packages/colony-js-client/src/ColonyClient/senders/SetAdminRole.js
  packages/colony-js-client/src/ColonyClient/senders/SetFounderRole.js
Labels: bug, under-review

#399 Various fixes
  CHANGELOG.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/callers/GetExtensionAddress.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyClient/senders/DomainAuth.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/TokenLockingClient/index.js
  packages/colony-js-contract-client/src/__tests__/paramTypes.js
  packages/colony-js-contract-client/src/flowtypes/params.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
Labels: bug, under-review

#400 Generate and add docs on precommit
  docs/_API_ColonyClient.md
  docs/_API_TokenLockingClient.md
  package.json
Labels: enhancement, ready-for-review

#402 Update dependencies and package configuration
  .circleci/config.yml
  .nvmrc
  lerna.json
  package.json
  packages/colony-js-adapter-ethers/jest.conf.json
  packages/colony-js-adapter-ethers/package.json
  packages/colony-js-adapter-ethers/src/EthersAdapter.js
  packages/colony-js-adapter-ethers/src/EthersContract.js
  packages/colony-js-adapter/package.json
  packages/colony-js-client/jest.conf.json
  packages/colony-js-client/package.json
  packages/colony-js-client/src/ColonyClient/callers/GetTask.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyClient/senders/AddPayment.js
  packages/colony-js-client/src/ColonyClient/senders/AddTask.js
  packages/colony-js-client/src/ColonyClient/senders/DomainAuth.js
  packages/colony-js-client/src/ColonyClient/senders/MakePayment.js
  packages/colony-js-client/src/ColonyClient/senders/SetFounderRole.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/TokenClient/callers/GetTokenInfo.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/TokenLockingClient/index.js
  packages/colony-js-client/src/getNetworkClient.js
  packages/colony-js-client/src/index.js
  packages/colony-js-client/src/lib/EthersWrappedWallet/index.js
  packages/colony-js-contract-client/jest.conf.json
  packages/colony-js-contract-client/package.json
  packages/colony-js-contract-client/src/__tests__/ContractClient.js
  packages/colony-js-contract-client/src/__tests__/ContractEvent.js
  packages/colony-js-contract-client/src/__tests__/ContractMethodSender.js
  packages/colony-js-contract-client/src/classes/ContractClient.js
  packages/colony-js-contract-client/src/classes/ContractEvent.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractMethodCaller.js
  packages/colony-js-contract-client/src/classes/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/classes/ContractMethodSender.js
  packages/colony-js-contract-client/src/classes/MultisigOperation.js
  packages/colony-js-contract-client/src/flowtypes/index.js
  packages/colony-js-contract-client/src/flowtypes/params.js
  packages/colony-js-contract-client/src/mocks/MockEmittingContract.js
  packages/colony-js-contract-client/src/modules/paramConversion.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
  packages/colony-js-contract-client/src/modules/paramValidation.js
  packages/colony-js-contract-loader-fs/jest.conf.json
  packages/colony-js-contract-loader-fs/package.json
  packages/colony-js-contract-loader-fs/src/loaders/FSLoader.js
  packages/colony-js-contract-loader-fs/src/loaders/TruffleLoader.js
  packages/colony-js-contract-loader-http/jest.conf.json
  packages/colony-js-contract-loader-http/package.json
  packages/colony-js-contract-loader-http/src/loaders/HttpLoader.js
  packages/colony-js-contract-loader-network/jest.conf.json
  packages/colony-js-contract-loader-network/package.json
  packages/colony-js-contract-loader/jest.conf.json
  packages/colony-js-contract-loader/package.json
  packages/colony-js-contract-loader/src/ContractLoader.js
  packages/colony-js-utils/jest.conf.json
  packages/colony-js-utils/package.json
  yarn.lock
Labels: maintenance, ready-for-review

#403 Add TokenClient isLocked caller and unlock sender
  docs/_API_TokenClient.md
  packages/colony-js-client/src/TokenClient/index.js
Labels: enhancement, ready-for-review

#405 Include contracts dir when publishing NetworkLoader, add Goerli deployment
  .flowconfig
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/IColonyNetwork.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/IMetaColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/IRecovery.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/ITokenLocking.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/OldRoles.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/OldRolesFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/OneTxPayment.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/OneTxPaymentFactory.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/Token.json
  packages/colony-js-contract-loader-network/contracts/versioned/goerli-v1/TokenAuthority.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/DSToken.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/OneTxPayment.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/Token.json
  packages/colony-js-contract-loader-network/package.json
  packages/colony-js-contract-loader-network/src/NetworkLoader.js
Labels: bug

#406 Support Goerli Infura provider in getNetworkClient
  packages/colony-js-client/src/getNetworkClient.js
  packages/colony-js-contract-loader-network/src/NetworkLoader.js
  packages/colony-js-contract-loader-network/src/__tests__/NetworkLoader.test.js
Labels: bug, under-review

#387 Update IPFS usage to reflect changes from v0.35.0
  docs/_Topics_UsingIPFS.md
Labels: documentation

#407 Add goerli network information
  packages/colony-js-client/src/getNetworkClient.js
Labels: bug

#404 Documentation updates for latest release
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  docs/_API_ContractClient.md
  docs/_API_TokenClient.md
  docs/_API_TokenLockingClient.md
  docs/_Components_Adapters.md
  docs/_Components_Clients.md
  docs/_Components_Loaders.md
  docs/_Intro_GetStarted.md
  docs/_Intro_LocalSetup.md
  docs/_Intro_Welcome.md
  docs/_Topics_ColonyRoles.md
  docs/_Topics_DomainsAndSkills.md
  docs/_Topics_ManagingPermissions.md
  docs/_Topics_ReputationAndRewards.md
  docs/_Topics_TaskLifecycle.md
  docs/_Topics_TasksAndPayments.md
  docs/_Topics_TokensAndFunding.md
  docs/_Topics_UsingIPFS.md
  docs/_Topics_UsingMultisignature.md
  docs/_Topics_ViewingReputation.md
  lerna.json
  package.json
  packages/colony-js-adapter-ethers/README.md
  packages/colony-js-client/README.md
  packages/colony-js-client/docs/_API_ColonyClient.template.md
  packages/colony-js-client/docs/_API_ColonyNetworkClient.template.md
  packages/colony-js-client/docs/_API_TokenClient.template.md
  packages/colony-js-client/docs/_API_TokenLockingClient.template.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/TokenLockingClient/index.js
  yarn.lock
Labels: documentation

#413 Fix EthersAdapter getTransactionReceipt
  packages/colony-js-adapter-ethers/src/EthersAdapter.js
Labels: bug, ready-for-review

#415 Fix DomainAuth sender to account for defaultValues
  CHANGELOG.md
  packages/colony-js-client/src/ColonyClient/senders/DomainAuth.js
Labels: bug, ready-for-review

#412 Fix associated number values for colony roles
  docs/_Topics_ColonyRoles.md
Labels: documentation
