Repository JoinColony/colonyJS, pull requests merged in 2019-01, with the labels that each got.

#336 Fix task payout events to return amounts as BigNumbers
  CHANGELOG.md
  docs/_API_ColonyClient.md
  packages/colony-js-client/src/ColonyClient/index.js
Labels: bug, ready-for-review

#331 Update versions in "Get Started" doc
  docs/_Docs_GetStarted.md
Labels: ready-for-review

#332 Update and add contract client methods
  CHANGELOG.md
  docs/_API_ColonyClient.md
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/__tests__/ColonyClient.test.js
  packages/colony-js-contract-client/src/flowtypes/params.js
  packages/colony-js-contract-client/src/modules/paramTypes.js
Labels: ready-for-review

#345 Update client event and method descriptions
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  docs/_API_MetaColonyClient.md
  docs/_API_TokenClient.md
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/MetaColonyClient/index.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/addRecoveryMethods.js
Labels: ready-for-review

#346 Add contract info and update client methods
  docs/_API_ColonyClient.md
  docs/_API_ColonyNetworkClient.md
  docs/_API_MetaColonyClient.md
  docs/_API_TokenClient.md
  packages/colony-js-client/scripts/docgen.js
  packages/colony-js-client/src/ColonyClient/callers/GetTask.js
  packages/colony-js-client/src/ColonyClient/index.js
  packages/colony-js-client/src/ColonyClient/senders/CreateTask.js
  packages/colony-js-client/src/ColonyNetworkClient/index.js
  packages/colony-js-client/src/ColonyNetworkClient/senders/CreateToken.js
  packages/colony-js-client/src/MetaColonyClient/index.js
  packages/colony-js-client/src/TokenClient/callers/GetTokenInfo.js
  packages/colony-js-client/src/TokenClient/index.js
  packages/colony-js-client/src/addTokenLockingMethods.js
  packages/colony-js-contract-client/src/classes/ContractMethod.js
  packages/colony-js-contract-client/src/classes/ContractMethodCaller.js
  packages/colony-js-contract-client/src/classes/ContractMethodMultisigSender.js
  packages/colony-js-contract-client/src/classes/ContractMethodSender.js
  packages/colony-js-contract-client/src/classes/MultisigOperation.js
Labels: under-review
